### ISSUE TITLE
Hello author, can you solve the problem that `Aussiemon/ljd` cannot operate luac64 files?

### ISSUE THREAD

**Issue by etjson** [ii14/ljd#1]
Hello author, can you solve the problem that `Aussiemon/ljd` cannot operate luac64 files?

[https://github.com/Aussiemon/ljd](https://github.com/Aussiemon/ljd)

[https://github.com/Aussiemon/ljd/issues/5](https://github.com/Aussiemon/ljd/issues/5)

Sorry to bother you, I am not capable of solving this problem.

**Comment by ii14** [comment]
This is a completely different project. This is a debugger, not a bytecode decompiler.

I will change the name of the project to avoid confusion in the future.
